name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Enhancement'
    label: 'engancement'
  - title: 'Bug Fixes'
    labels:
      - 'bugfix'
      - 'hotfix'
  - title: 'Frontend'
    label: 'frontend'
  - title: 'Backend'
    label: 'backend'
  - title: 'Dependency Updates'
    label: 'dependencies'
  - title: 'Configs'
    label: 'config'
  - title: 'Legals'
    label: 'legal'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES